# Generated by Django 5.0.2 on 2024-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_upload',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_file', models.FileField(upload_to='chat_files/')),
                ('chat_startdatetime', models.DateTimeField()),
                ('chat_startampm', models.CharField(max_length=2)),
                ('chat_enddatetime', models.DateTimeField()),
                ('chat_endampm', models.CharField(max_length=2)),
            ],
        ),
    ]
