# Generated by Django 5.0.2 on 2024-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_upload',
            name='chat_enddatetime',
        ),
        migrations.RemoveField(
            model_name='chat_upload',
            name='chat_startdatetime',
        ),
        migrations.AddField(
            model_name='chat_upload',
            name='chat_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat_upload',
            name='chat_endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat_upload',
            name='chat_startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat_upload',
            name='chat_starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat_upload',
            name='chat_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
