# Generated by Django 5.0.2 on 2024-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0003_remove_chat_upload_chat_endampm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_upload',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
