# Generated by Django 5.0.2 on 2024-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0005_alter_chat_upload_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_upload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat_upload',
            name='chat_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
