# Generated by Django 5.0.2 on 2024-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0007_alter_chat_upload_chat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_upload',
            name='chat_file',
            field=models.FileField(upload_to='data/ipdata/'),
        ),
    ]
