# Generated by Django 5.0.2 on 2024-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0008_alter_chat_upload_chat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_upload',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
