# Generated by Django 5.0.2 on 2024-04-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0012_alter_chat_upload_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_upload',
            name='is_active',
        ),
    ]
