# Generated by Django 5.0.2 on 2024-05-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0013_remove_chat_upload_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_upload',
            name='chat_endtime',
        ),
        migrations.RemoveField(
            model_name='chat_upload',
            name='chat_starttime',
        ),
    ]
