# Generated by Django 5.0.2 on 2024-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_upload', '0014_remove_chat_upload_chat_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_upload',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
